// Copyright 2026 Andrew Yates.
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! Generated from TLA+ module: BCP
#![allow(clippy::clone_double_ref, suspicious_double_ref_op)]
//!
//! This file was auto-generated by tla-codegen (TIR path).
//! Source: `tla2 codegen --tir --config specs/z4/MCBCP_noDeadlock.cfg specs/z4/BCP.tla`
//!
//! Do not edit manually.
//!
//! ## Benchmark Results (Part of #3730)
//!
//! BFS state exploration of 32 reachable states (3-var, 4-clause SAT instance).
//! Criterion benchmark on Apple M-series, `--release`:
//!
//! | Variant                          | Time (median) |
//! |----------------------------------|---------------|
//! | Generated BFS                    | ~172 us       |
//! | Handwritten BFS                  | ~20 us        |
//! | Generated BFS + invariants       | ~820 us       |
//! | Handwritten BFS + invariants     | ~36 us        |
//!
//! The ~8.7x overhead comes primarily from:
//! - `TlaFunc<i64, String>` (BTreeMap) vs `[Assign; 3]` (stack array)
//! - `String` comparisons ("TRUE"/"FALSE"/"UNSET") vs enum discriminant
//! - `TlaSet<TlaSet<i64>>` (BTreeSet) vs `&[&[i32]]` (static slices)
//! - Per-call `clauses()` reconstruction vs static CLAUSES constant
//!
//! The invariant overhead (~5x for generated) is dominated by TypeOK which
//! enumerates the full function set `[1..3 -> {"TRUE","FALSE","UNSET"}]`
//! (27 functions) on every state check.

#![allow(unused)]

use tla_runtime::prelude::*;

// Constants from config
fn clauses() -> TlaSet<TlaSet<i64>> {
    tla_set![
        tla_set![1_i64, 2_i64],
        tla_set![-1_i64, 3_i64],
        tla_set![-2_i64, -3_i64],
        tla_set![1_i64, -2_i64, 3_i64]
    ]
}
fn num_vars() -> i64 {
    3_i64
}

/// State for BCP
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct BCPState {
    pub assignment: TlaFunc<i64, String>,
    pub trail: Vec<(i64, String, TlaSet<i64>)>,
    pub conflict: bool,
    pub propagating: bool,
}

/// State machine for BCP
pub struct BCP;

impl StateMachine for BCP {
    type State = BCPState;

    fn init(&self) -> Vec<Self::State> {
        vec![Self::State {
            assignment: TlaFunc::from_iter(range_set(1_i64, num_vars()).iter().map(|__v| {
                let v = __v.clone();
                (v.clone(), "UNSET".to_string())
            })),
            trail: vec![],
            conflict: false,
            propagating: true,
        }]
    }

    fn next(&self, state: &Self::State) -> Vec<Self::State> {
        let mut next_states = Vec::new();
        // Action 1
        if (state.propagating == true) && (state.conflict == false) {
            for c in clauses() {
                if Self::clause_unit(state, &c) {
                    let lit = Self::unit_lit(state, &c);
                    let v = Self::var(&lit);
                    let val = Self::lit_value(&lit);
                    next_states.push(Self::State {
                        assignment: state.assignment.except(v.clone(), val.clone()),
                        trail: {
                            let mut __s = state.trail.clone();
                            __s.push((v, val, c));
                            __s
                        },
                        conflict: false,
                        propagating: true,
                    });
                }
            }
        }
        // Action 2
        if (state.propagating == true)
            && (state.conflict == false)
            && clauses().iter().any(|__c| {
                let c = __c.clone();
                Self::clause_conflict(state, &c)
            })
        {
            next_states.push(Self::State {
                assignment: state.assignment.clone(),
                trail: state.trail.clone(),
                conflict: true,
                propagating: false,
            });
        }
        // Action 3
        if (state.propagating == true)
            && (state.conflict == false)
            && !clauses().iter().any(|__c| {
                let c = __c.clone();
                Self::clause_unit(state, &c)
            })
            && !clauses().iter().any(|__c| {
                let c = __c.clone();
                Self::clause_conflict(state, &c)
            })
        {
            next_states.push(Self::State {
                assignment: state.assignment.clone(),
                trail: state.trail.clone(),
                conflict: state.conflict.clone(),
                propagating: false,
            });
        }
        // Action 4
        if (state.propagating == false) && (state.conflict == false) {
            for v in range_set(1_i64, num_vars()) {
                if (state
                    .assignment
                    .apply(&v)
                    .cloned()
                    .expect("function application requires key in domain")
                    == "UNSET".to_string())
                {
                    for __val in tla_set!["TRUE".to_string(), "FALSE".to_string()] {
                        let val = __val.clone();
                        next_states.push(Self::State {
                            assignment: state.assignment.except(v.clone(), val.clone()),
                            trail: {
                                let mut __s = state.trail.clone();
                                __s.push((v, val, TlaSet::new()));
                                __s
                            },
                            conflict: false,
                            propagating: true,
                        });
                    }
                }
            }
        }
        // Action 5
        if ((state.conflict == true)
            || ((state.propagating == false)
                && range_set(1_i64, num_vars()).iter().all(|__v| {
                    let v = __v.clone();
                    (state
                        .assignment
                        .apply(&v)
                        .cloned()
                        .expect("function application requires key in domain")
                        != "UNSET".to_string())
                })))
        {
            next_states.push(Self::State {
                assignment: state.assignment.clone(),
                trail: state.trail.clone(),
                conflict: state.conflict.clone(),
                propagating: state.propagating.clone(),
            });
        }
        next_states
    }

    fn invariant_names(&self) -> Vec<&'static str> {
        vec![
            "TypeOK",
            "TrailConsistent",
            "NoSpuriousConflict",
            "PropagationSound",
        ]
    }

    fn check_named_invariant(&self, name: &str, state: &Self::State) -> Option<bool> {
        match name {
            "TypeOK" => Some(BCP::check_type_o_k(state)),
            "TrailConsistent" => Some(BCP::check_trail_consistent(state)),
            "NoSpuriousConflict" => Some(BCP::check_no_spurious_conflict(state)),
            "PropagationSound" => Some(BCP::check_propagation_sound(state)),
            _ => None,
        }
    }

    fn check_invariant(&self, state: &Self::State) -> Option<bool> {
        Some(
            BCP::check_type_o_k(state)
                && BCP::check_trail_consistent(state)
                && BCP::check_no_spurious_conflict(state)
                && BCP::check_propagation_sound(state),
        )
    }
}

impl BCP {
    fn check_type_o_k(state: &BCPState) -> bool {
        (({
            let __domain: Vec<_> = (range_set(1_i64, num_vars())).iter().cloned().collect();
            let __range: Vec<_> =
                (tla_set!["TRUE".to_string(), "FALSE".to_string(), "UNSET".to_string()])
                    .iter()
                    .cloned()
                    .collect();
            let __dom_len = __domain.len();
            let __range_len = __range.len();
            if __dom_len > 10
                || __range_len
                    .checked_pow(__dom_len as u32)
                    .map_or(true, |n| n > 10000)
            {
                panic!(
                    "FuncSet too large: domain_size={}, range_size={}",
                    __dom_len, __range_len
                );
            }
            let mut __result = TlaSet::new();
            let __total = __range_len.pow(__dom_len as u32);
            for __i in 0..__total {
                let mut __f_entries = Vec::new();
                let mut __n = __i;
                for __d in &__domain {
                    __f_entries.push((__d.clone(), __range[__n % __range_len].clone()));
                    __n /= __range_len;
                }
                __result.insert(TlaFunc::from_iter(__f_entries));
            }
            __result
        }
        .contains(&state.assignment)
            && boolean_set().contains(&state.conflict))
            && boolean_set().contains(&state.propagating))
    }

    fn check_trail_consistent(state: &BCPState) -> bool {
        range_set(1_i64, (state.trail.len() as i64))
            .iter()
            .all(|__i| {
                let i = __i.clone();
                {
                    let entry = state.trail[(i as usize) - 1].clone();
                    let v = entry.0;
                    let val = entry.1;
                    (state
                        .assignment
                        .apply(&v)
                        .cloned()
                        .expect("function application requires key in domain")
                        == val)
                }
            })
    }

    fn check_no_spurious_conflict(state: &BCPState) -> bool {
        (!state.conflict
            || clauses().iter().any(|__c| {
                let c = __c.clone();
                Self::clause_conflict(state, &c)
            }))
    }

    fn check_propagation_sound(state: &BCPState) -> bool {
        range_set(1_i64, (state.trail.len() as i64))
            .iter()
            .all(|__i| {
                let i = __i.clone();
                {
                    let entry = state.trail[(i as usize) - 1].clone();
                    let v = entry.0;
                    let val = entry.1;
                    let reason = entry.2;
                    clauses().iter().all(|__c| {
                        let c = __c.clone();
                        (!(reason == c)
                            || c.iter().any(|__lit| {
                                let lit = __lit.clone();
                                ((Self::var(&lit) == v) && (Self::lit_value(&lit) == val))
                            }))
                    })
                }
            })
    }
}

// Helper operators
impl BCP {
    fn positive(lit: &i64) -> bool {
        let lit = lit.clone();
        let __r = (lit > 0_i64);
        __r
    }

    fn unit_lit(state: &BCPState, c: &TlaSet<i64>) -> i64 {
        let c = c.clone();
        let __r = c
            .iter()
            .find(|__lit| {
                let lit = __lit.clone();
                Self::lit_unset(state, &lit)
            })
            .cloned()
            .expect("CHOOSE: no element satisfies predicate");
        __r
    }

    fn var(lit: &i64) -> i64 {
        let lit = lit.clone();
        let __r = if (lit > 0_i64) { lit } else { (-lit) };
        __r
    }

    fn clause_conflict(state: &BCPState, c: &TlaSet<i64>) -> bool {
        let c = c.clone();
        let __r = c.iter().all(|__lit| {
            let lit = __lit.clone();
            Self::lit_false(state, &lit)
        });
        __r
    }

    fn lit_true(state: &BCPState, lit: &i64) -> bool {
        let lit = lit.clone();
        let __r = {
            let v = Self::var(&lit);
            if Self::positive(&lit) {
                (state
                    .assignment
                    .apply(&v)
                    .cloned()
                    .expect("function application requires key in domain")
                    == "TRUE".to_string())
            } else {
                (state
                    .assignment
                    .apply(&v)
                    .cloned()
                    .expect("function application requires key in domain")
                    == "FALSE".to_string())
            }
        };
        __r
    }

    fn clause_unit(state: &BCPState, c: &TlaSet<i64>) -> bool {
        let c = c.clone();
        let __r = (!Self::clause_sat(state, &c)
            && ((TlaSet::from_iter(
                c.iter()
                    .filter(|__lit| {
                        let lit = __lit.clone();
                        Self::lit_unset(state, &lit)
                    })
                    .cloned(),
            )
            .len() as i64)
                == 1_i64));
        __r
    }

    fn clause_sat(state: &BCPState, c: &TlaSet<i64>) -> bool {
        let c = c.clone();
        let __r = c.iter().any(|__lit| {
            let lit = __lit.clone();
            Self::lit_true(state, &lit)
        });
        __r
    }

    fn lit_false(state: &BCPState, lit: &i64) -> bool {
        let lit = lit.clone();
        let __r = {
            let v = Self::var(&lit);
            if Self::positive(&lit) {
                (state
                    .assignment
                    .apply(&v)
                    .cloned()
                    .expect("function application requires key in domain")
                    == "FALSE".to_string())
            } else {
                (state
                    .assignment
                    .apply(&v)
                    .cloned()
                    .expect("function application requires key in domain")
                    == "TRUE".to_string())
            }
        };
        __r
    }

    fn lit_unset(state: &BCPState, lit: &i64) -> bool {
        let lit = lit.clone();
        let __r = (state
            .assignment
            .apply(&Self::var(&lit))
            .cloned()
            .expect("function application requires key in domain")
            == "UNSET".to_string());
        __r
    }

    fn lit_value(lit: &i64) -> String {
        let lit = lit.clone();
        let __r = if Self::positive(&lit) {
            "TRUE".to_string()
        } else {
            "FALSE".to_string()
        };
        __r
    }
}

fn main() {}
