// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Generalized Buchi Automaton (GBA) construction from LTL NNF formulas.
//!
//! Implements a simplified GPVW (Gerth-Peled-Vardi-Wolper) on-the-fly
//! construction with transition-based acceptance.
//!
//! ## Acceptance semantics
//!
//! For each Until sub-formula `φ U ψ`, the acceptance condition requires
//! that the run infinitely often visits a state/edge where the Until is
//! "discharged" — i.e., ψ was satisfied. In the standard GPVW formulation,
//! a state q is accepting for `φ U ψ` if:
//!
//! 1. `φ U ψ ∉ q` (the Until is not an obligation of q), **OR**
//! 2. The transition was generated by choosing `ψ` (Branch 1), discharging
//!    the Until obligation at this step.
//!
//! Condition 2 is critical for formulas like `G(X(F(p)))`, where the `G`
//! operator (Release) re-introduces the `F(p)` (Until) obligation at every
//! step via `Next`. Without edge-based acceptance, no state in the G regime
//! can satisfy condition 1, making the acceptance unsatisfiable even when
//! `p` holds infinitely often.

use rustc_hash::{FxHashMap, FxHashSet};

#[cfg(test)]
use super::atoms::LtlContext;
use super::nnf::LtlNnf;

/// A state in the GBA, identified by its "next" obligation set.
pub(super) type GbaStateId = u32;

/// Generalized Buchi Automaton.
pub(super) struct Gba {
    /// Number of states.
    pub num_states: u32,
    /// Initial transitions from virtual initial node to GBA states (with guards).
    pub initial_transitions: Vec<GbaTransition>,
    /// Transitions: `transitions[state]` = list of (guard, successor).
    /// Guard is a function from system state to bool.
    pub transitions: Vec<Vec<GbaTransition>>,
    /// Acceptance sets: for each Until sub-formula, the set of GBA states
    /// where the acceptance condition is satisfied (state-based acceptance).
    pub acceptance: Vec<FxHashSet<GbaStateId>>,
}

pub(super) struct GbaTransition {
    /// Which atoms must hold (positive) or not hold (negative) in the system state.
    pub pos_atoms: Vec<usize>,
    pub neg_atoms: Vec<usize>,
    /// Successor GBA state.
    pub successor: GbaStateId,
    /// Edge-based acceptance: `edge_accept[i]` is true if this transition
    /// discharges Until sub-formula `i` (took Branch 1 for that Until during
    /// expansion). Used together with state-based acceptance for correct
    /// handling of `G(X(F(...)))` patterns.
    pub edge_accept: Vec<bool>,
}

#[cfg(test)]
impl GbaTransition {
    pub fn guard_satisfied(&self, ctx: &LtlContext<'_>, sys_state: u32) -> bool {
        self.pos_atoms.iter().all(|&a| ctx.atom_holds(a, sys_state))
            && self
                .neg_atoms
                .iter()
                .all(|&a| !ctx.atom_holds(a, sys_state))
    }
}

/// Build a GBA from an NNF LTL formula.
pub(super) fn build_gba(formula: &LtlNnf) -> Gba {
    // Collect all Until sub-formulas for acceptance conditions.
    let mut until_formulas: Vec<LtlNnf> = Vec::new();
    collect_untils(formula, &mut until_formulas);
    let num_accept = until_formulas.len();

    // State map: "next obligation set" → state ID
    let mut state_map: FxHashMap<Vec<LtlNnf>, GbaStateId> = FxHashMap::default();
    let mut transitions: Vec<Vec<GbaTransition>> = Vec::new();
    let mut acceptance: Vec<FxHashSet<GbaStateId>> =
        vec![FxHashSet::default(); until_formulas.len()];

    // Work queue for states to expand
    let mut queue: Vec<Vec<LtlNnf>> = Vec::new();

    // Generate initial transitions by expanding the formula.
    // The "initial state" is virtual — we compute transitions from it
    // to find the actual GBA initial states.
    let mut initial_expansions: Vec<ExpansionResult> = Vec::new();
    expand_formula(
        std::slice::from_ref(formula),
        Vec::new(),
        Vec::new(),
        Vec::new(),
        vec![false; num_accept],
        &until_formulas,
        &mut initial_expansions,
    );

    let mut initial_transitions: Vec<GbaTransition> = Vec::new();
    for exp in &initial_expansions {
        let mut sorted_next = exp.next_obligations.clone();
        sorted_next.sort();
        sorted_next.dedup();

        let sid = get_or_create_state(
            &mut state_map,
            &mut transitions,
            &mut queue,
            &sorted_next,
            &until_formulas,
            &mut acceptance,
        );
        initial_transitions.push(GbaTransition {
            pos_atoms: exp.pos_atoms.clone(),
            neg_atoms: exp.neg_atoms.clone(),
            successor: sid,
            edge_accept: exp.discharged.clone(),
        });
    }

    // BFS to discover all reachable GBA states.
    let mut processed = 0;
    while processed < queue.len() {
        let next_set = queue[processed].clone();
        let sid = state_map[&next_set];
        processed += 1;

        // Expand the formulas in this state's obligation set.
        let mut expansions: Vec<ExpansionResult> = Vec::new();
        if next_set.is_empty() {
            // No obligations — self-loop with no guard (always enabled)
            expansions.push(ExpansionResult {
                pos_atoms: Vec::new(),
                neg_atoms: Vec::new(),
                next_obligations: Vec::new(),
                discharged: vec![false; num_accept],
            });
        } else {
            expand_formula(
                &next_set,
                Vec::new(),
                Vec::new(),
                Vec::new(),
                vec![false; num_accept],
                &until_formulas,
                &mut expansions,
            );
        }

        let mut trans = Vec::new();
        for exp in &expansions {
            let mut sorted = exp.next_obligations.clone();
            sorted.sort();
            sorted.dedup();

            let succ_id = get_or_create_state(
                &mut state_map,
                &mut transitions,
                &mut queue,
                &sorted,
                &until_formulas,
                &mut acceptance,
            );

            trans.push(GbaTransition {
                pos_atoms: exp.pos_atoms.clone(),
                neg_atoms: exp.neg_atoms.clone(),
                successor: succ_id,
                edge_accept: exp.discharged.clone(),
            });
        }
        transitions[sid as usize] = trans;
    }

    Gba {
        num_states: state_map.len() as u32,
        initial_transitions,
        transitions,
        acceptance,
    }
}

fn get_or_create_state(
    state_map: &mut FxHashMap<Vec<LtlNnf>, GbaStateId>,
    transitions: &mut Vec<Vec<GbaTransition>>,
    queue: &mut Vec<Vec<LtlNnf>>,
    next_set: &[LtlNnf],
    until_formulas: &[LtlNnf],
    acceptance: &mut [FxHashSet<GbaStateId>],
) -> GbaStateId {
    let key = next_set.to_vec();
    if let Some(&id) = state_map.get(&key) {
        return id;
    }
    let id = state_map.len() as GbaStateId;
    state_map.insert(key, id);
    transitions.push(Vec::new());
    queue.push(next_set.to_vec());

    // Acceptance: state is accepting for set i if Until formula i
    // is NOT among this state's obligations.
    for (i, uf) in until_formulas.iter().enumerate() {
        if !next_set.contains(uf) {
            acceptance[i].insert(id);
        }
    }

    id
}

/// Collect all Until sub-formulas (for acceptance conditions).
fn collect_untils(formula: &LtlNnf, result: &mut Vec<LtlNnf>) {
    match formula {
        LtlNnf::Until(a, b) => {
            if !result.contains(formula) {
                result.push(formula.clone());
            }
            collect_untils(a, result);
            collect_untils(b, result);
        }
        LtlNnf::Release(a, b) => {
            collect_untils(a, result);
            collect_untils(b, result);
        }
        LtlNnf::And(children) | LtlNnf::Or(children) => {
            for c in children {
                collect_untils(c, result);
            }
        }
        LtlNnf::Next(inner) => collect_untils(inner, result),
        LtlNnf::Atom(_) | LtlNnf::NegAtom(_) | LtlNnf::True | LtlNnf::False => {}
    }
}

/// Result of expanding a set of LTL formulas.
struct ExpansionResult {
    pos_atoms: Vec<usize>,
    neg_atoms: Vec<usize>,
    next_obligations: Vec<LtlNnf>,
    /// Which Until sub-formulas were discharged (Branch 1 taken) during
    /// this expansion path. `discharged[i]` corresponds to `until_formulas[i]`.
    discharged: Vec<bool>,
}

/// Expand a set of LTL formulas into expansion results.
///
/// This is the core of the GPVW algorithm: process each formula to determine
/// what atoms must hold now and what obligations carry to the next step.
/// Also tracks which Until sub-formulas are discharged (Branch 1 taken)
/// for edge-based acceptance.
fn expand_formula(
    to_process: &[LtlNnf],
    pos_atoms: Vec<usize>,
    neg_atoms: Vec<usize>,
    next_obligations: Vec<LtlNnf>,
    discharged: Vec<bool>,
    until_formulas: &[LtlNnf],
    results: &mut Vec<ExpansionResult>,
) {
    if to_process.is_empty() {
        results.push(ExpansionResult {
            pos_atoms,
            neg_atoms,
            next_obligations,
            discharged,
        });
        return;
    }

    let formula = &to_process[0];
    let rest = &to_process[1..];

    match formula {
        LtlNnf::True => {
            expand_formula(
                rest,
                pos_atoms,
                neg_atoms,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::False => {
            // Contradiction — this branch dies
        }
        LtlNnf::Atom(id) => {
            if neg_atoms.contains(id) {
                return; // Contradiction
            }
            let mut new_pos = pos_atoms.clone();
            if !new_pos.contains(id) {
                new_pos.push(*id);
            }
            expand_formula(
                rest,
                new_pos,
                neg_atoms,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::NegAtom(id) => {
            if pos_atoms.contains(id) {
                return; // Contradiction
            }
            let mut new_neg = neg_atoms.clone();
            if !new_neg.contains(id) {
                new_neg.push(*id);
            }
            expand_formula(
                rest,
                pos_atoms,
                new_neg,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::And(children) => {
            let mut combined: Vec<LtlNnf> = children.clone();
            combined.extend_from_slice(rest);
            expand_formula(
                &combined,
                pos_atoms,
                neg_atoms,
                next_obligations,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::Or(children) => {
            // Nondeterministic choice: try each child
            for child in children {
                let mut branch: Vec<LtlNnf> = vec![child.clone()];
                branch.extend_from_slice(rest);
                expand_formula(
                    &branch,
                    pos_atoms.clone(),
                    neg_atoms.clone(),
                    next_obligations.clone(),
                    discharged.clone(),
                    until_formulas,
                    results,
                );
            }
        }
        LtlNnf::Next(inner) => {
            let mut new_next = next_obligations.clone();
            new_next.push(*inner.clone());
            expand_formula(
                rest,
                pos_atoms,
                neg_atoms,
                new_next,
                discharged,
                until_formulas,
                results,
            );
        }
        LtlNnf::Until(a, b) => {
            // a U b: either b holds now, OR (a holds now AND X(a U b))
            // Branch 1: b holds now (Until discharged)
            {
                let mut branch: Vec<LtlNnf> = vec![*b.clone()];
                branch.extend_from_slice(rest);
                // Mark this Until as discharged for edge acceptance
                let mut new_discharged = discharged.clone();
                if let Some(idx) = until_formulas.iter().position(|uf| uf == formula) {
                    new_discharged[idx] = true;
                }
                expand_formula(
                    &branch,
                    pos_atoms.clone(),
                    neg_atoms.clone(),
                    next_obligations.clone(),
                    new_discharged,
                    until_formulas,
                    results,
                );
            }
            // Branch 2: a holds now, obligation continues
            {
                let mut branch: Vec<LtlNnf> = vec![*a.clone()];
                branch.extend_from_slice(rest);
                let mut new_next = next_obligations.clone();
                new_next.push(formula.clone());
                expand_formula(
                    &branch,
                    pos_atoms,
                    neg_atoms,
                    new_next,
                    discharged,
                    until_formulas,
                    results,
                );
            }
        }
        LtlNnf::Release(a, b) => {
            // a R b: b must hold now, AND (a holds now OR X(a R b))
            // Branch 1: b AND a hold now (release satisfied)
            {
                let mut branch: Vec<LtlNnf> = vec![*b.clone(), *a.clone()];
                branch.extend_from_slice(rest);
                expand_formula(
                    &branch,
                    pos_atoms.clone(),
                    neg_atoms.clone(),
                    next_obligations.clone(),
                    discharged.clone(),
                    until_formulas,
                    results,
                );
            }
            // Branch 2: b holds now, obligation continues
            {
                let mut branch: Vec<LtlNnf> = vec![*b.clone()];
                branch.extend_from_slice(rest);
                let mut new_next = next_obligations.clone();
                new_next.push(formula.clone());
                expand_formula(
                    &branch,
                    pos_atoms,
                    neg_atoms,
                    new_next,
                    discharged,
                    until_formulas,
                    results,
                );
            }
        }
    }
}

#[cfg(test)]
#[path = "gba_tests.rs"]
mod gba_tests;
