// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! `tla2 coverage` -- model checking coverage analysis.
//!
//! Reads a JSON output file produced by `tla2 check --output json` and reports
//! which actions (Next disjuncts) were exercised during model checking, how many
//! states each generated, and what percentage of actions were explored.
//!
//! Two data sources are used:
//! 1. `actions_detected` — per-action occurrence counts from the JSON output
//! 2. Counterexample trace states — action names from the trace (when present)
//!
//! When a TLA+ spec file is provided (`--spec`), the command cross-references
//! detected actions against the actual Next disjuncts defined in the spec to
//! identify unexplored actions.

use std::collections::HashMap;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;
use tla_check::{ActionInfo, JsonOutput};

use crate::cli_schema::CoverageOutputFormat;

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Run the coverage analysis command.
pub(crate) fn cmd_coverage(
    trace_file: &Path,
    spec: Option<&Path>,
    config: Option<&Path>,
    format: CoverageOutputFormat,
) -> Result<()> {
    // 1. Read and parse the JSON output file.
    let json_content = std::fs::read_to_string(trace_file)
        .with_context(|| format!("Failed to read trace file: {}", trace_file.display()))?;

    let output: JsonOutput = serde_json::from_str(&json_content)
        .with_context(|| format!("Failed to parse JSON from: {}", trace_file.display()))?;

    // 2. Build the coverage analysis.
    let analysis = build_coverage_analysis(&output, spec, config)?;

    // 3. Emit output.
    match format {
        CoverageOutputFormat::Human => print_human_coverage(&analysis),
        CoverageOutputFormat::Json => {
            let json = serde_json::to_string_pretty(&analysis)
                .context("Failed to serialize coverage analysis to JSON")?;
            println!("{json}");
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Analysis types
// ---------------------------------------------------------------------------

/// Complete coverage analysis result.
#[derive(Debug, Serialize)]
struct CoverageAnalysis {
    /// Source file that was checked.
    spec_file: String,
    /// Module name.
    module: String,
    /// Overall status of the check.
    status: String,
    /// Total states found during model checking.
    total_states: usize,
    /// Total transitions.
    total_transitions: usize,
    /// Per-action coverage metrics.
    actions: Vec<ActionCoverage>,
    /// Actions defined in the spec but never exercised (requires --spec).
    #[serde(skip_serializing_if = "Vec::is_empty")]
    uncovered_actions: Vec<String>,
    /// Summary metrics.
    summary: CoverageSummary,
}

/// Coverage metrics for a single action.
#[derive(Debug, Serialize)]
struct ActionCoverage {
    /// Action name (e.g., "Increment", "Decrement").
    name: String,
    /// Action ID (e.g., "detected:0").
    #[serde(skip_serializing_if = "String::is_empty")]
    id: String,
    /// Number of state transitions generated by this action.
    occurrences: usize,
    /// Percentage of all transitions attributed to this action.
    percentage: f64,
    /// First BFS level where this action was observed (from trace, if available).
    #[serde(skip_serializing_if = "Option::is_none")]
    first_seen_level: Option<usize>,
    /// Last BFS level where this action was observed (from trace, if available).
    #[serde(skip_serializing_if = "Option::is_none")]
    last_seen_level: Option<usize>,
}

/// Summary of overall action coverage.
#[derive(Debug, Serialize)]
struct CoverageSummary {
    /// Total number of distinct actions observed.
    actions_exercised: usize,
    /// Total number of actions defined in the spec (requires --spec).
    #[serde(skip_serializing_if = "Option::is_none")]
    actions_defined: Option<usize>,
    /// Fraction of defined actions that were exercised (requires --spec).
    #[serde(skip_serializing_if = "Option::is_none")]
    coverage_ratio: Option<f64>,
    /// The most frequently exercised action.
    #[serde(skip_serializing_if = "Option::is_none")]
    hottest_action: Option<String>,
    /// The least frequently exercised action (among those exercised).
    #[serde(skip_serializing_if = "Option::is_none")]
    coldest_action: Option<String>,
    /// Wall-clock time of the model checking run.
    time_seconds: f64,
    /// Maximum BFS depth reached.
    #[serde(skip_serializing_if = "Option::is_none")]
    max_depth: Option<usize>,
}

// ---------------------------------------------------------------------------
// Analysis builder
// ---------------------------------------------------------------------------

/// Build the coverage analysis from parsed JSON output and optional spec.
fn build_coverage_analysis(
    output: &JsonOutput,
    spec_path: Option<&Path>,
    config_path: Option<&Path>,
) -> Result<CoverageAnalysis> {
    let total_states = output.statistics.states_found;
    let total_transitions = output.statistics.transitions;

    // Build per-action coverage from actions_detected.
    let mut actions: Vec<ActionCoverage> = if !output.actions_detected.is_empty() {
        build_from_actions_detected(&output.actions_detected, total_transitions)
    } else if let Some(ce) = &output.counterexample {
        // Fall back: infer from counterexample trace action names.
        build_from_trace_actions(&ce.states)
    } else {
        Vec::new()
    };

    // If we have a counterexample trace, augment with first/last seen levels.
    if let Some(ce) = &output.counterexample {
        augment_with_trace_levels(&mut actions, &ce.states);
    }

    // Sort actions by occurrences descending (hottest first).
    actions.sort_by(|a, b| b.occurrences.cmp(&a.occurrences));

    // Cross-reference with spec disjuncts if --spec is provided.
    let (spec_disjuncts, uncovered_actions) = if let Some(spec) = spec_path {
        cross_reference_spec(spec, config_path, &actions)?
    } else {
        (None, Vec::new())
    };

    let actions_exercised = actions.len();

    let hottest_action = actions.first().map(|a| a.name.clone());
    let coldest_action = actions
        .iter()
        .filter(|a| a.occurrences > 0)
        .min_by_key(|a| a.occurrences)
        .map(|a| a.name.clone());

    let coverage_ratio = spec_disjuncts.map(|total| {
        if total == 0 {
            1.0
        } else {
            actions_exercised as f64 / total as f64
        }
    });

    let summary = CoverageSummary {
        actions_exercised,
        actions_defined: spec_disjuncts,
        coverage_ratio,
        hottest_action,
        coldest_action,
        time_seconds: output.statistics.time_seconds,
        max_depth: output.statistics.max_depth,
    };

    Ok(CoverageAnalysis {
        spec_file: output.input.spec_file.clone(),
        module: output.input.module.clone(),
        status: output.result.status.clone(),
        total_states,
        total_transitions,
        actions,
        uncovered_actions,
        summary,
    })
}

/// Build action coverage from the `actions_detected` field.
fn build_from_actions_detected(
    actions: &[ActionInfo],
    total_transitions: usize,
) -> Vec<ActionCoverage> {
    actions
        .iter()
        .map(|a| {
            let percentage = if let Some(pct) = a.percentage {
                pct
            } else if total_transitions > 0 {
                (a.occurrences as f64 / total_transitions as f64) * 100.0
            } else {
                0.0
            };
            ActionCoverage {
                name: a.name.clone(),
                id: a.id.clone(),
                occurrences: a.occurrences,
                percentage,
                first_seen_level: None,
                last_seen_level: None,
            }
        })
        .collect()
}

/// Infer action coverage from counterexample trace state actions.
fn build_from_trace_actions(
    states: &[tla_check::StateInfo],
) -> Vec<ActionCoverage> {
    let mut action_counts: HashMap<String, usize> = HashMap::new();

    for state in states {
        if state.action.action_type != "initial" {
            *action_counts
                .entry(state.action.name.clone())
                .or_insert(0) += 1;
        }
    }

    let total: usize = action_counts.values().sum();
    action_counts
        .into_iter()
        .map(|(name, count)| {
            let percentage = if total > 0 {
                (count as f64 / total as f64) * 100.0
            } else {
                0.0
            };
            ActionCoverage {
                name,
                id: String::new(),
                occurrences: count,
                percentage,
                first_seen_level: None,
                last_seen_level: None,
            }
        })
        .collect()
}

/// Augment action coverage with first/last seen BFS levels from the trace.
fn augment_with_trace_levels(
    actions: &mut [ActionCoverage],
    states: &[tla_check::StateInfo],
) {
    // Build a map of action_name -> (first_index, last_index) from trace states.
    let mut level_map: HashMap<&str, (usize, usize)> = HashMap::new();
    for state in states {
        if state.action.action_type == "initial" {
            continue;
        }
        let name = state.action.name.as_str();
        let level = state.index;
        level_map
            .entry(name)
            .and_modify(|(first, last)| {
                if level < *first {
                    *first = level;
                }
                if level > *last {
                    *last = level;
                }
            })
            .or_insert((level, level));
    }

    for action in actions.iter_mut() {
        if let Some(&(first, last)) = level_map.get(action.name.as_str()) {
            action.first_seen_level = Some(first);
            action.last_seen_level = Some(last);
        }
    }
}

/// Cross-reference detected actions with spec-defined Next disjuncts.
///
/// Returns `(total_defined, uncovered_names)`.
fn cross_reference_spec(
    spec_path: &Path,
    config_path: Option<&Path>,
    detected: &[ActionCoverage],
) -> Result<(Option<usize>, Vec<String>)> {
    let source = std::fs::read_to_string(spec_path)
        .with_context(|| format!("Failed to read spec file: {}", spec_path.display()))?;

    let tree = tla_core::parse_to_syntax_tree(&source);
    let lower_result = tla_core::lower(tla_core::FileId(0), &tree);
    if !lower_result.errors.is_empty() {
        // Cannot analyze spec structure; skip cross-referencing.
        return Ok((None, Vec::new()));
    }

    let module = match &lower_result.module {
        Some(m) => m,
        None => return Ok((None, Vec::new())),
    };

    // Determine the Next operator name from config or default.
    let next_name = resolve_next_name(config_path)?;

    // Extract disjuncts from the Next operator.
    let disjuncts = extract_disjuncts_from_module(module, &next_name);
    if disjuncts.is_empty() {
        return Ok((None, Vec::new()));
    }

    let total_defined = disjuncts.len();
    let detected_names: std::collections::HashSet<&str> =
        detected.iter().map(|a| a.name.as_str()).collect();

    let uncovered: Vec<String> = disjuncts
        .into_iter()
        .filter(|name| !detected_names.contains(name.as_str()))
        .collect();

    Ok((Some(total_defined), uncovered))
}

/// Resolve the Next operator name from a config file, defaulting to "Next".
fn resolve_next_name(config_path: Option<&Path>) -> Result<String> {
    if let Some(cfg_path) = config_path {
        if cfg_path.exists() {
            let cfg_source = std::fs::read_to_string(cfg_path)
                .with_context(|| format!("read config file: {}", cfg_path.display()))?;
            let config = tla_check::Config::parse(&cfg_source).map_err(|errors| {
                anyhow::anyhow!("config parse failed with {} error(s)", errors.len())
            })?;
            if let Some(next) = config.next {
                return Ok(next);
            }
        }
    }
    Ok("Next".to_string())
}

/// Extract disjunct names from a module's Next operator definition.
///
/// For `Next == A \/ B \/ C`, returns `["A", "B", "C"]` if each disjunct is
/// a simple operator application. For complex expressions, returns the
/// pretty-printed expression text.
fn extract_disjuncts_from_module(
    module: &tla_core::ast::Module,
    operator_name: &str,
) -> Vec<String> {
    for unit in &module.units {
        if let tla_core::ast::Unit::Operator(def) = &unit.node {
            if def.name.node == operator_name {
                return extract_disjuncts(&def.body.node);
            }
        }
    }
    Vec::new()
}

/// Recursively extract disjuncts from `A \/ B \/ C`.
fn extract_disjuncts(expr: &tla_core::ast::Expr) -> Vec<String> {
    match expr {
        tla_core::ast::Expr::Or(lhs, rhs) => {
            let mut result = extract_disjuncts(&lhs.node);
            result.extend(extract_disjuncts(&rhs.node));
            result
        }
        // If disjunct is a simple operator reference, use its name.
        tla_core::ast::Expr::Ident(name, _) => vec![name.clone()],
        // If disjunct is an operator application with no args (e.g., `Foo`),
        // try to extract a readable name.
        other => vec![tla_core::pretty_expr(other)],
    }
}

// ---------------------------------------------------------------------------
// Human-readable output
// ---------------------------------------------------------------------------

/// Print the coverage analysis in human-readable colored table format.
fn print_human_coverage(analysis: &CoverageAnalysis) {
    println!("=== Action Coverage Analysis ===");
    println!();
    println!(
        "Spec: {} (module {})",
        analysis.spec_file, analysis.module
    );
    println!("Status: {}", analysis.status);
    println!(
        "States: {}  |  Transitions: {}  |  Time: {:.2}s",
        format_number(analysis.total_states),
        format_number(analysis.total_transitions),
        analysis.summary.time_seconds,
    );
    if let Some(depth) = analysis.summary.max_depth {
        println!("Max BFS depth: {depth}");
    }
    println!();

    if analysis.actions.is_empty() {
        println!("No action coverage data available.");
        println!();
        println!("To collect coverage data, run:");
        println!("  tla2 check --coverage --output json <spec.tla> > output.json");
        println!("  tla2 coverage output.json");
        return;
    }

    // Print the action table.
    print_action_table(&analysis.actions, analysis.total_transitions);

    // Print summary.
    println!("--- Summary ---");
    println!();
    println!(
        "  Actions exercised: {}",
        analysis.summary.actions_exercised
    );
    if let Some(defined) = analysis.summary.actions_defined {
        let ratio = analysis.summary.coverage_ratio.unwrap_or(0.0);
        println!("  Actions defined:   {defined}");
        println!("  Coverage:          {:.1}%", ratio * 100.0);
    }
    if let Some(hot) = &analysis.summary.hottest_action {
        println!("  Hottest action:    {hot}");
    }
    if let Some(cold) = &analysis.summary.coldest_action {
        println!("  Coldest action:    {cold}");
    }
    println!();

    // Print uncovered actions if any.
    if !analysis.uncovered_actions.is_empty() {
        println!(
            "--- Uncovered Actions ({}) ---",
            analysis.uncovered_actions.len()
        );
        println!();
        for name in &analysis.uncovered_actions {
            println!("  [MISS] {name}");
        }
        println!();
    }
}

/// Print a formatted table of action coverage with ASCII bar chart.
fn print_action_table(actions: &[ActionCoverage], total_transitions: usize) {
    // Compute column widths.
    let max_name_len = actions
        .iter()
        .map(|a| a.name.len())
        .max()
        .unwrap_or(6)
        .max(6);

    let max_count_len = actions
        .iter()
        .map(|a| format_number(a.occurrences).len())
        .max()
        .unwrap_or(5)
        .max(5);

    // Header.
    println!(
        "  {:<name_w$}  {:>count_w$}  {:>6}  {:>5}  {:>5}  Bar",
        "Action",
        "Count",
        "Pct",
        "First",
        "Last",
        name_w = max_name_len,
        count_w = max_count_len,
    );
    println!(
        "  {:-<name_w$}  {:-<count_w$}  {:-<6}  {:-<5}  {:-<5}  {:-<30}",
        "",
        "",
        "",
        "",
        "",
        "",
        name_w = max_name_len,
        count_w = max_count_len,
    );

    // Find the max occurrences for bar scaling.
    let max_occurrences = actions
        .iter()
        .map(|a| a.occurrences)
        .max()
        .unwrap_or(1)
        .max(1);

    for action in actions {
        let percentage = if total_transitions > 0 {
            action.percentage
        } else {
            0.0
        };

        let first = action
            .first_seen_level
            .map(|l| format!("{l}"))
            .unwrap_or_else(|| "-".to_string());

        let last = action
            .last_seen_level
            .map(|l| format!("{l}"))
            .unwrap_or_else(|| "-".to_string());

        // ASCII bar: scale to 30 chars max.
        let bar_len = if max_occurrences > 0 {
            (action.occurrences as f64 / max_occurrences as f64 * 30.0).ceil() as usize
        } else {
            0
        };
        let bar: String = "#".repeat(bar_len.min(30));

        println!(
            "  {:<name_w$}  {:>count_w$}  {:>5.1}%  {:>5}  {:>5}  {bar}",
            action.name,
            format_number(action.occurrences),
            percentage,
            first,
            last,
            name_w = max_name_len,
            count_w = max_count_len,
        );
    }

    println!();
}

/// Format a number with comma separators for readability.
fn format_number(n: usize) -> String {
    let s = n.to_string();
    let mut result = String::with_capacity(s.len() + s.len() / 3);
    for (i, c) in s.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            result.push(',');
        }
        result.push(c);
    }
    result.chars().rev().collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_output_with_actions() -> JsonOutput {
        let json_str = r#"{
            "version": "1.3",
            "tool": "tla2",
            "timestamp": "2026-03-30T00:00:00Z",
            "input": {
                "spec_file": "Counter.tla",
                "module": "Counter",
                "workers": 1
            },
            "specification": {
                "invariants": ["TypeOK"],
                "properties": [],
                "constants": {},
                "variables": ["count"]
            },
            "soundness": {
                "mode": "sound",
                "features_used": [],
                "deviations": [],
                "assumptions": []
            },
            "completeness": "exhaustive",
            "result": {
                "status": "ok"
            },
            "actions_detected": [
                { "name": "Increment", "occurrences": 150, "percentage": 60.0 },
                { "name": "Decrement", "occurrences": 80, "percentage": 32.0 },
                { "name": "Reset", "occurrences": 20, "percentage": 8.0 }
            ],
            "statistics": {
                "states_found": 100,
                "states_initial": 1,
                "transitions": 250,
                "time_seconds": 0.5,
                "max_depth": 10
            },
            "diagnostics": {
                "warnings": [],
                "info": []
            }
        }"#;
        serde_json::from_str(json_str).expect("test JSON should parse")
    }

    fn make_test_output_no_actions() -> JsonOutput {
        let json_str = r#"{
            "version": "1.3",
            "tool": "tla2",
            "timestamp": "2026-03-30T00:00:00Z",
            "input": {
                "spec_file": "Simple.tla",
                "module": "Simple",
                "workers": 1
            },
            "specification": {
                "invariants": ["TypeOK"],
                "properties": [],
                "constants": {},
                "variables": ["x"]
            },
            "soundness": {
                "mode": "sound",
                "features_used": [],
                "deviations": [],
                "assumptions": []
            },
            "completeness": "exhaustive",
            "result": {
                "status": "error",
                "error_type": "invariant_violation",
                "error_code": "TLC_INVARIANT_VIOLATION",
                "error_message": "Invariant TypeOK is violated.",
                "violated_property": {
                    "name": "TypeOK",
                    "type": "invariant"
                }
            },
            "counterexample": {
                "length": 3,
                "states": [
                    {
                        "index": 1,
                        "action": { "name": "Initial predicate", "type": "initial" },
                        "variables": { "x": { "type": "int", "value": 0 } }
                    },
                    {
                        "index": 2,
                        "action": { "name": "StepA", "type": "next" },
                        "variables": { "x": { "type": "int", "value": 1 } }
                    },
                    {
                        "index": 3,
                        "action": { "name": "StepB", "type": "next" },
                        "variables": { "x": { "type": "int", "value": -1 } }
                    }
                ]
            },
            "statistics": {
                "states_found": 5,
                "states_initial": 1,
                "transitions": 4,
                "time_seconds": 0.01
            },
            "diagnostics": {
                "warnings": [],
                "info": []
            }
        }"#;
        serde_json::from_str(json_str).expect("test JSON should parse")
    }

    #[test]
    fn test_coverage_from_actions_detected() {
        let output = make_test_output_with_actions();
        let analysis = build_coverage_analysis(&output, None, None).unwrap();

        assert_eq!(analysis.actions.len(), 3);
        assert_eq!(analysis.total_states, 100);
        assert_eq!(analysis.total_transitions, 250);

        // Should be sorted by occurrences descending.
        assert_eq!(analysis.actions[0].name, "Increment");
        assert_eq!(analysis.actions[0].occurrences, 150);
        assert!((analysis.actions[0].percentage - 60.0).abs() < 0.1);

        assert_eq!(analysis.actions[1].name, "Decrement");
        assert_eq!(analysis.actions[1].occurrences, 80);

        assert_eq!(analysis.actions[2].name, "Reset");
        assert_eq!(analysis.actions[2].occurrences, 20);

        assert_eq!(analysis.summary.actions_exercised, 3);
        assert_eq!(
            analysis.summary.hottest_action.as_deref(),
            Some("Increment")
        );
        assert_eq!(analysis.summary.coldest_action.as_deref(), Some("Reset"));
    }

    #[test]
    fn test_coverage_fallback_to_trace() {
        let output = make_test_output_no_actions();
        let analysis = build_coverage_analysis(&output, None, None).unwrap();

        // Should infer from trace: StepA (1 occurrence), StepB (1 occurrence).
        assert_eq!(analysis.actions.len(), 2);
        let names: Vec<&str> = analysis.actions.iter().map(|a| a.name.as_str()).collect();
        assert!(names.contains(&"StepA"));
        assert!(names.contains(&"StepB"));
    }

    #[test]
    fn test_coverage_trace_levels() {
        let output = make_test_output_no_actions();
        let analysis = build_coverage_analysis(&output, None, None).unwrap();

        // StepA first/last seen at index 2, StepB at index 3.
        let step_a = analysis.actions.iter().find(|a| a.name == "StepA").unwrap();
        assert_eq!(step_a.first_seen_level, Some(2));
        assert_eq!(step_a.last_seen_level, Some(2));

        let step_b = analysis.actions.iter().find(|a| a.name == "StepB").unwrap();
        assert_eq!(step_b.first_seen_level, Some(3));
        assert_eq!(step_b.last_seen_level, Some(3));
    }

    #[test]
    fn test_format_number_with_commas() {
        assert_eq!(format_number(0), "0");
        assert_eq!(format_number(999), "999");
        assert_eq!(format_number(1_000), "1,000");
        assert_eq!(format_number(1_000_000), "1,000,000");
        assert_eq!(format_number(123_456_789), "123,456,789");
    }

    #[test]
    fn test_coverage_empty_output() {
        let json_str = r#"{
            "version": "1.3",
            "tool": "tla2",
            "timestamp": "2026-03-30T00:00:00Z",
            "input": {
                "spec_file": "Empty.tla",
                "module": "Empty",
                "workers": 1
            },
            "specification": {
                "invariants": [],
                "properties": [],
                "constants": {},
                "variables": []
            },
            "soundness": {
                "mode": "sound",
                "features_used": [],
                "deviations": [],
                "assumptions": []
            },
            "completeness": "exhaustive",
            "result": {
                "status": "ok"
            },
            "statistics": {
                "states_found": 0,
                "states_initial": 0,
                "transitions": 0,
                "time_seconds": 0.001
            },
            "diagnostics": {
                "warnings": [],
                "info": []
            }
        }"#;
        let output: JsonOutput = serde_json::from_str(json_str).unwrap();
        let analysis = build_coverage_analysis(&output, None, None).unwrap();

        assert!(analysis.actions.is_empty());
        assert_eq!(analysis.summary.actions_exercised, 0);
        assert!(analysis.summary.hottest_action.is_none());
        assert!(analysis.summary.coldest_action.is_none());
    }

    #[test]
    fn test_coverage_json_serialization() {
        let output = make_test_output_with_actions();
        let analysis = build_coverage_analysis(&output, None, None).unwrap();

        let json = serde_json::to_string_pretty(&analysis).unwrap();
        assert!(json.contains("\"actions_exercised\": 3"));
        assert!(json.contains("\"Increment\""));
        assert!(json.contains("\"Decrement\""));
        assert!(json.contains("\"Reset\""));
        assert!(json.contains("\"total_transitions\": 250"));
    }
}
