// Copyright 2026 Andrew Yates.
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0
#![forbid(unsafe_code)]

//! TLA+ Proof Certificate Checker
//!
//! This crate provides a minimal, trusted proof certificate checker.
//! Proof certificates are generated by automated provers (Zenon, SMT solvers)
//! and can be independently verified by this checker.
//!
//! # Design Goals
//!
//! 1. **Minimal**: Small codebase (~3000 lines), easy to audit
//! 2. **Trusted**: Small trusted computing base
//! 3. **Independent**: Verifies proofs without trusting the prover
//!
//! # Certificate Format
//!
//! Certificates are sequences of proof steps, each justified by:
//! - Axioms (built-in logical rules)
//! - Previously proven steps (modus ponens, etc.)
//! - Definitions (from the specification)
//!
//! # Module Structure
//!
//! - [`types`]: Data types for certificates, formulas, terms, and verification results
//! - [`checker`]: The certificate verification engine
//! - [`axiom_check`]: Axiom verification logic
//! - [`formula_ops`]: Formula operations (substitution, alpha-equivalence, unification)

mod axiom_check;
mod checker;
mod formula_ops;
mod types;

pub use checker::CertificateChecker;
pub use formula_ops::alpha_equiv;
pub use types::{
    ArithmeticAxiom, Axiom, Backend, Certificate, CertificateIoError, CertificateStep, Formula,
    Justification, SetAxiom, StepId, Term, VerificationError, VerificationResult,
};

#[cfg(test)]
mod tests;
