// Copyright 2026 Andrew Yates.
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! VMT (Verification Modulo Theories) output format for external model checkers.
#![allow(dead_code)]
//!
//! VMT is an extension of SMT-LIB2 used by hardware model checkers such as
//! nuXmv and IC3Ref. It annotates standard SMT-LIB2 declarations with:
//! - `:next` — links current-state to next-state variables
//! - `:init` — marks the initial state formula
//! - `:trans` — marks the transition relation
//! - `:invar-property` — marks invariant properties to check
//!
//! Reference: <https://vmt-lib.fbk.eu/>
//!
//! Part of #3755.

use std::fmt::Write;

use tla_core::ast::{Expr, Module, OperatorDef, Unit};
use tla_core::Spanned;

use super::vmt_sort::{collect_and_infer_vars, domain_sort};

/// Sort of a VMT state variable, inferred from TLA+ constraints.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum VmtSort {
    Bool,
    Int,
}

impl VmtSort {
    pub(super) fn smtlib_name(self) -> &'static str {
        match self {
            VmtSort::Bool => "Bool",
            VmtSort::Int => "Int",
        }
    }
}

/// A state variable with inferred sort.
#[derive(Debug, Clone)]
pub(super) struct VmtVar {
    pub(super) name: String,
    pub(super) sort: VmtSort,
}

/// Context for VMT translation carrying resolved operator definitions.
struct VmtCtx<'a> {
    module: &'a Module,
    vars: Vec<VmtVar>,
}

impl<'a> VmtCtx<'a> {
    /// Find an operator definition by name in the module.
    fn find_operator(&self, name: &str) -> Option<&'a OperatorDef> {
        for unit in &self.module.units {
            if let Unit::Operator(def) = &unit.node {
                if def.name.node == name {
                    return Some(def);
                }
            }
        }
        None
    }

    /// Check if a name is a state variable.
    fn is_state_var(&self, name: &str) -> bool {
        self.vars.iter().any(|v| v.name == name)
    }
}

/// Generate VMT output from a parsed TLA+ module and configuration.
///
/// Returns the VMT string or an error message if the spec cannot be translated.
pub(crate) fn spec_to_vmt(
    module: &Module,
    init_name: &str,
    next_name: &str,
    invariant_names: &[String],
) -> Result<String, String> {
    let vars = collect_and_infer_vars(module, init_name)?;
    if vars.is_empty() {
        return Err("No state variables declared in module".to_string());
    }

    let ctx = VmtCtx { module, vars };

    let mut out = String::new();

    // Header comment.
    writeln!(out, "; VMT output generated by TLA2").unwrap();
    writeln!(out, "; Module: {}", module.name.node).unwrap();
    writeln!(out, "; Init: {init_name}, Next: {next_name}").unwrap();
    writeln!(out).unwrap();

    // Declare current-state variables.
    for var in &ctx.vars {
        writeln!(
            out,
            "(declare-fun {} () {})",
            smtlib_ident(&var.name),
            var.sort.smtlib_name()
        )
        .unwrap();
    }

    // Declare next-state variables.
    for var in &ctx.vars {
        writeln!(
            out,
            "(declare-fun {}_next () {})",
            smtlib_ident(&var.name),
            var.sort.smtlib_name()
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    // Translate Init predicate.
    let init_body = ctx
        .find_operator(init_name)
        .ok_or_else(|| format!("Init operator '{}' not found", init_name))?;
    if !init_body.params.is_empty() {
        return Err(format!(
            "Init operator '{}' must be parameterless for VMT export",
            init_name
        ));
    }
    let init_smt = expr_to_smtlib(&init_body.body, &ctx, false)?;
    writeln!(out, "(define-fun .init () Bool {})", init_smt).unwrap();
    writeln!(out).unwrap();

    // Translate Next relation (with primed vars mapped to _next).
    let next_body = ctx
        .find_operator(next_name)
        .ok_or_else(|| format!("Next operator '{}' not found", next_name))?;
    if !next_body.params.is_empty() {
        return Err(format!(
            "Next operator '{}' must be parameterless for VMT export",
            next_name
        ));
    }
    let next_smt = expr_to_smtlib(&next_body.body, &ctx, false)?;
    writeln!(out, "(define-fun .trans () Bool {})", next_smt).unwrap();
    writeln!(out).unwrap();

    // Translate invariant properties.
    for (i, inv_name) in invariant_names.iter().enumerate() {
        let inv_body = ctx
            .find_operator(inv_name)
            .ok_or_else(|| format!("Invariant operator '{}' not found", inv_name))?;
        if !inv_body.params.is_empty() {
            return Err(format!(
                "Invariant operator '{}' must be parameterless for VMT export",
                inv_name
            ));
        }
        let inv_smt = expr_to_smtlib(&inv_body.body, &ctx, false)?;
        writeln!(
            out,
            "(define-fun .prop{} () Bool {})",
            if invariant_names.len() > 1 {
                format!("_{i}")
            } else {
                String::new()
            },
            inv_smt
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    // VMT annotations.
    writeln!(out, "; VMT annotations").unwrap();
    for var in &ctx.vars {
        writeln!(
            out,
            "(! {} :next {}_next)",
            smtlib_ident(&var.name),
            smtlib_ident(&var.name)
        )
        .unwrap();
    }
    writeln!(out, "(! .init :init true)").unwrap();
    writeln!(out, "(! .trans :trans true)").unwrap();
    for i in 0..invariant_names.len() {
        let prop_name = if invariant_names.len() > 1 {
            format!(".prop_{i}")
        } else {
            ".prop".to_string()
        };
        writeln!(out, "(! {} :invar-property {})", prop_name, i).unwrap();
    }

    Ok(out)
}

/// Translate a TLA+ expression to SMT-LIB2 string.
///
/// `in_prime` indicates whether we are inside a primed context (Prime wrapping).
fn expr_to_smtlib(
    expr: &Spanned<Expr>,
    ctx: &VmtCtx<'_>,
    in_prime: bool,
) -> Result<String, String> {
    match &expr.node {
        // Literals
        Expr::Bool(true) => Ok("true".to_string()),
        Expr::Bool(false) => Ok("false".to_string()),
        Expr::Int(n) => {
            let s = n.to_string();
            if s.starts_with('-') {
                Ok(format!("(- {})", &s[1..]))
            } else {
                Ok(s)
            }
        }

        // Variables
        Expr::Ident(name, _) | Expr::StateVar(name, _, _) => {
            if ctx.is_state_var(name) {
                if in_prime {
                    Ok(format!("{}_next", smtlib_ident(name)))
                } else {
                    Ok(smtlib_ident(name))
                }
            } else {
                // Could be an operator reference — try to inline.
                if let Some(def) = ctx.find_operator(name) {
                    if def.params.is_empty() {
                        return expr_to_smtlib(&def.body, ctx, in_prime);
                    }
                }
                // Constants like BOOLEAN, TRUE, FALSE handled above as Bool.
                // For unresolved identifiers, emit as-is.
                Ok(smtlib_ident(name))
            }
        }

        // Prime: x' maps to x_next
        Expr::Prime(inner) => expr_to_smtlib(inner, ctx, true),

        // Logic
        Expr::And(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(and {} {})", la, lb))
        }
        Expr::Or(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(or {} {})", la, lb))
        }
        Expr::Not(a) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            Ok(format!("(not {})", la))
        }
        Expr::Implies(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(=> {} {})", la, lb))
        }
        Expr::Equiv(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(= {} {})", la, lb))
        }

        // Comparison
        Expr::Eq(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(= {} {})", la, lb))
        }
        Expr::Neq(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(not (= {} {}))", la, lb))
        }
        Expr::Lt(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(< {} {})", la, lb))
        }
        Expr::Leq(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(<= {} {})", la, lb))
        }
        Expr::Gt(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(> {} {})", la, lb))
        }
        Expr::Geq(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(>= {} {})", la, lb))
        }

        // Arithmetic
        Expr::Add(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(+ {} {})", la, lb))
        }
        Expr::Sub(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(- {} {})", la, lb))
        }
        Expr::Mul(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(* {} {})", la, lb))
        }
        Expr::Div(a, b) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!("(div {} {})", la, lb))
        }
        Expr::IntDiv(a, b) => {
            // TLA+ \div is floor division; SMT-LIB `div` is Euclidean.
            // Adjust: when divisor < 0 and remainder exists, subtract 1.
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!(
                "(let ((__a {}) (__b {})) \
                 (ite (and (< __b 0) (distinct (* (div __a __b) __b) __a)) \
                 (- (div __a __b) 1) (div __a __b)))",
                la, lb
            ))
        }
        Expr::Mod(a, b) => {
            // TLA+ mod always returns non-negative for positive divisor.
            // Defensive adjustment for negative Euclidean remainder.
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            let lb = expr_to_smtlib(b, ctx, in_prime)?;
            Ok(format!(
                "(let ((__r (mod {} {}))) \
                 (ite (< __r 0) (+ __r {}) __r))",
                la, lb, lb
            ))
        }
        Expr::Neg(a) => {
            let la = expr_to_smtlib(a, ctx, in_prime)?;
            Ok(format!("(- {})", la))
        }

        // Control
        Expr::If(cond, then_br, else_br) => {
            let sc = expr_to_smtlib(cond, ctx, in_prime)?;
            let st = expr_to_smtlib(then_br, ctx, in_prime)?;
            let se = expr_to_smtlib(else_br, ctx, in_prime)?;
            Ok(format!("(ite {} {} {})", sc, st, se))
        }

        // UNCHANGED <<x, y>> => x_next = x /\ y_next = y
        Expr::Unchanged(vars_expr) => translate_unchanged(vars_expr, ctx),

        // Let-in: inline the body
        Expr::Let(defs, body) => {
            // For simple parameterless let-defs, we can inline.
            // Complex cases with parameters fall through to unsupported.
            if defs.iter().all(|d| d.params.is_empty()) {
                // The body will resolve let-bound names via find_operator
                // in the module, but let-local names won't be there.
                // For now, just translate the body directly.
                expr_to_smtlib(body, ctx, in_prime)
            } else {
                Err(format!(
                    "Unsupported: LET with parameterized definitions in VMT export"
                ))
            }
        }

        // Label: transparent wrapper
        Expr::Label(label) => expr_to_smtlib(&label.body, ctx, in_prime),

        // Operator application: inline if parameterless
        Expr::Apply(op, args) => {
            if let Expr::Ident(name, _) | Expr::StateVar(name, _, _) = &op.node {
                if let Some(def) = ctx.find_operator(name) {
                    if def.params.is_empty() && args.is_empty() {
                        return expr_to_smtlib(&def.body, ctx, in_prime);
                    }
                }
            }
            Err(format!(
                "Unsupported: operator application in VMT export (only basic TLA+ supported)"
            ))
        }

        // Quantifiers (bounded)
        Expr::Forall(bounds, body) => {
            if bounds.len() != 1 {
                return Err("Unsupported: multi-variable forall in VMT export".to_string());
            }
            let bound = &bounds[0];
            let var_name = smtlib_ident(&bound.name.node);
            let domain = bound
                .domain
                .as_ref()
                .ok_or("Unsupported: unbounded forall in VMT export")?;
            let sort = domain_sort(domain)?;
            let body_smt = expr_to_smtlib(body, ctx, in_prime)?;
            Ok(format!(
                "(forall (({} {})) {})",
                var_name,
                sort.smtlib_name(),
                body_smt
            ))
        }
        Expr::Exists(bounds, body) => {
            if bounds.len() != 1 {
                return Err("Unsupported: multi-variable exists in VMT export".to_string());
            }
            let bound = &bounds[0];
            let var_name = smtlib_ident(&bound.name.node);
            let domain = bound
                .domain
                .as_ref()
                .ok_or("Unsupported: unbounded exists in VMT export")?;
            let sort = domain_sort(domain)?;
            let body_smt = expr_to_smtlib(body, ctx, in_prime)?;
            Ok(format!(
                "(exists (({} {})) {})",
                var_name,
                sort.smtlib_name(),
                body_smt
            ))
        }

        // Fallback for unsupported expressions.
        other => Err(format!(
            "Unsupported TLA+ expression for VMT export: {:?}",
            std::mem::discriminant(other)
        )),
    }
}

/// Translate `UNCHANGED <<x, y>>` or `UNCHANGED x` to SMT-LIB2.
fn translate_unchanged(vars_expr: &Spanned<Expr>, _ctx: &VmtCtx<'_>) -> Result<String, String> {
    let var_names = extract_unchanged_vars(vars_expr)?;
    if var_names.is_empty() {
        return Err("UNCHANGED with no variables".to_string());
    }

    let conjuncts: Vec<String> = var_names
        .iter()
        .map(|name| format!("(= {}_next {})", smtlib_ident(name), smtlib_ident(name)))
        .collect();

    if conjuncts.len() == 1 {
        Ok(conjuncts.into_iter().next().expect("non-empty"))
    } else {
        Ok(format!("(and {})", conjuncts.join(" ")))
    }
}

/// Extract variable names from an UNCHANGED expression.
fn extract_unchanged_vars(expr: &Spanned<Expr>) -> Result<Vec<String>, String> {
    match &expr.node {
        Expr::Ident(name, _) | Expr::StateVar(name, _, _) => Ok(vec![name.clone()]),
        Expr::Tuple(elements) => {
            let mut names = Vec::new();
            for elem in elements {
                names.extend(extract_unchanged_vars(elem)?);
            }
            Ok(names)
        }
        _ => Err("Unsupported UNCHANGED expression form in VMT export".to_string()),
    }
}

/// Sanitize a TLA+ identifier for use in SMT-LIB2.
///
/// SMT-LIB2 allows alphanumeric identifiers plus `_`. Identifiers containing
/// special characters are quoted with `|...|`.
pub(crate) fn smtlib_ident(name: &str) -> String {
    if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !name.is_empty()
        && !name.starts_with(|c: char| c.is_ascii_digit())
    {
        name.to_string()
    } else {
        format!("|{}|", name)
    }
}
