// Copyright 2026 Andrew Yates.
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! `impl ModelChecker` bridge methods for TIR parity/eval.

use super::*;

impl<'a> ModelChecker<'a> {
    pub(in crate::check::model_checker) fn cached_next_uses_tir_eval(&self) -> bool {
        let Some(raw_next_name) = self
            .trace
            .cached_next_name
            .as_deref()
            .or(self.config.next.as_deref())
        else {
            return false;
        };
        let resolved_next_name = self.ctx.resolve_op_name(raw_next_name);
        self.tir_parity.as_ref().is_some_and(|tir| {
            tir.selected_named_op_uses_tir_eval_name(raw_next_name, resolved_next_name)
        })
    }

    pub(in crate::check::model_checker) fn maybe_check_tir_parity_state(
        &mut self,
        name: &str,
        state: &ArrayState,
    ) -> Result<(), CheckError> {
        let Some(parity) = self.tir_parity.as_ref() else {
            return Ok(());
        };
        if !parity.is_parity_mode() || !parity.is_selected(name) {
            return Ok(());
        }

        let _state_guard = self.ctx.bind_state_env_guard(state.env_ref());
        parity
            .assert_matches_ast(&self.ctx, name)
            .map_err(|err| EvalCheckError::Eval(err).into())
    }

    pub(in crate::check::model_checker) fn maybe_check_tir_parity_transition(
        &mut self,
        name: &str,
        current: &ArrayState,
        next: &ArrayState,
    ) -> Result<(), CheckError> {
        let Some(parity) = self.tir_parity.as_ref() else {
            return Ok(());
        };
        if !parity.is_parity_mode() || !parity.is_selected(name) {
            return Ok(());
        }

        let _state_guard = self.ctx.bind_state_env_guard(current.env_ref());
        let _next_guard = self.ctx.bind_next_state_env_guard(next.env_ref());
        parity
            .assert_matches_ast(&self.ctx, name)
            .map_err(|err| EvalCheckError::Eval(err).into())
    }

    pub(in crate::check::model_checker) fn transition_holds_via_tir(
        &mut self,
        name: &str,
        current: &ArrayState,
        next: &ArrayState,
    ) -> Result<bool, CheckError> {
        let Some(tir) = self.tir_parity.as_ref() else {
            return Ok(true);
        };
        let resolved_name = self.ctx.resolve_op_name(name).to_string();
        let Some(program) = tir.make_tir_program_for_selected_eval_name(name, &resolved_name)
        else {
            return Ok(true);
        };

        let _state_guard = self.ctx.bind_state_env_guard(current.env_ref());
        let _next_guard = self.ctx.bind_next_state_env_guard(next.env_ref());
        // Part of #3264: Call TIR eval for probe recording only. The result
        // is NOT used to filter successors because TIR cannot properly
        // evaluate transition predicates containing primed variables (x').
        // The successor was already correctly generated by the AST
        // enumerator — using the TIR result as a filter causes false
        // deadlocks on specs with replacement-resolved operators.
        let _ = program.eval_named_op(&self.ctx, &resolved_name);
        Ok(true)
    }
}
