// Copyright 2026 Dropbox
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Per-action branching metrics and oracle routing decisions for CDEMC.
//!
//! Contains threshold constants, the `OracleDecision` enum, and the
//! `ActionMetrics` struct used by BFS and the oracle to make routing
//! decisions.

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

// =========================================================================
// Oracle decision types and threshold constants (Part of #3785)
// =========================================================================

/// Minimum number of evaluations required before the oracle considers
/// branching-factor data reliable enough to route actions away from BFS.
/// Below this threshold, the action stays on `UseBfs` to gather more data.
///
/// Part of #3785.
pub(crate) const MIN_EVALUATIONS_FOR_ROUTING: u64 = 5;

/// Convergence rate threshold: if BFS is discovering new states at a rate
/// above this fraction of total states per depth level, BFS is still
/// productive and the oracle avoids routing actions to symbolic.
///
/// A value of 0.1 means "if >10% of discovered states at the current depth
/// are new, BFS is converging well."
///
/// Part of #3785.
pub(crate) const CONVERGENCE_RATE_THRESHOLD: f64 = 0.1;

/// Oracle routing decision for a single action in the next-state relation.
///
/// This enum is not z4-gated so it can be used by BFS code to make
/// routing decisions without requiring the symbolic engine feature.
///
/// Part of #3785.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub(crate) enum OracleDecision {
    /// Action should be handled by BFS explicit-state exploration.
    ///
    /// Reasons: not SMT-compatible, low branching factor, insufficient
    /// data, or BFS is converging rapidly.
    UseBfs,
    /// Action should be handled by the symbolic (z4) engine.
    ///
    /// Reasons: high branching factor AND SMT-compatible AND BFS
    /// convergence has slowed.
    UseSymbolic,
    /// Action can be handled by either engine. Defaults to BFS unless
    /// the symbolic engine has spare capacity.
    ///
    /// Reasons: SMT-compatible with moderate branching factor.
    UseBoth,
}

/// Per-action branching metrics for oracle routing decisions.
///
/// Populated by BFS during exploration, read by the oracle to identify
/// high-branching actions suitable for symbolic handling.
pub(crate) struct ActionMetrics {
    /// Total successor states generated by this action across all firings.
    pub(crate) total_successors: AtomicU64,
    /// Number of times this action was evaluated (fired from any state).
    pub(crate) times_evaluated: AtomicU64,
    /// Whether this action's expressions are within the SMT-compatible fragment.
    /// Set once at startup based on static analysis; never changes at runtime.
    pub(crate) smt_compatible: AtomicBool,
    /// Whether this action has been JIT-compiled to native code via Cranelift.
    ///
    /// Set by the model checker after successful JIT compilation of the
    /// action's next-state relation. JIT-compiled actions execute faster
    /// in BFS and should be preferred for `BfsOnly` routing by the oracle.
    ///
    /// Part of #3854.
    pub(crate) jit_compiled: AtomicBool,
}

impl ActionMetrics {
    /// Record that this action produced `successor_count` successors from one
    /// firing. Thread-safe: uses relaxed atomics (advisory metrics, not
    /// correctness-critical).
    ///
    /// Part of #3784.
    #[inline]
    pub(crate) fn record_firing(&self, successor_count: u64) {
        self.times_evaluated.fetch_add(1, Ordering::Relaxed);
        self.total_successors
            .fetch_add(successor_count, Ordering::Relaxed);
    }

    /// Average branching factor for this action (successors per firing).
    ///
    /// Returns `0.0` if the action has never been evaluated.
    ///
    /// Part of #3784.
    pub(crate) fn branching_factor(&self) -> f64 {
        let evals = self.times_evaluated.load(Ordering::Relaxed);
        if evals == 0 {
            return 0.0;
        }
        self.total_successors.load(Ordering::Relaxed) as f64 / evals as f64
    }
}
